### ISSUE TITLE
Issues with Version 5 - Missing Features and Label Printing Process

### ISSUE THREAD

**Issue by MikeFeith** [Progressus-io/postnl-for-woocommerce#118]
Dear Developers,
After updating to version 5 of the plugin, we have encountered several issues that have significantly affected our workflow.

**Unfranked Labels Option Missing:** Previously, we had the ability to print unfranked labels, a feature we used extensively for non-package mailbox posts(Where we add a sticker to the envelope). This option, available since v1.5, appears to have been removed without prior notification.

**Label Printing Process:** The new version has altered the label printing process. Earlier, labels would open directly in the browser, allowing for immediate printing. However, the new version requires the labels to be downloaded before printing, which has disrupted our workflow.

**Delivery to PostNL Point:** Since we enabled the option for delivery to a PostNL point, every package now presents this option regardless of its applicability. This is an issue for regular packages, mailbox packages, and other posts that may not be suitable for this delivery point.

We are eager to know if these issues, particularly the absence of the unfranked label printing feature, will be addressed in the near future. Additionally, in the event that these issues persist, could you please inform us how long version 4 will continue to be supported? We are forced to keep using that version for now.

Looking forward to your prompt response.

Kind regards,
Haken en Maken

**Comment by Kratos-Hosting** [comment]
Hi, this issue has been open for months yet no-one commented on this issue. Please at least add the "Unfranked Labels (ongefrankeerd)" option...

**Comment by Abdalsalaam** [comment]
Hello @MikeFeith and @Kratos-Hosting 
I forwarded this issue to Postnl team since it need a business decision, and I'll let you know when we release these features.
