### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by patrickinterwijs** [Progressus-io/postnl-for-woocommerce#139]
Dear developers,
We are using the plugin, and when entering an incorrect address, we consistently receive the English translation: 'Address does not contain house number!' Please add a Dutch translation for this because it is not included in the translation file. 
Thank you in advance.

**Comment by Abdalsalaam** [comment]
@patrickinterwijs thank you for reporting this, we got it and it will be fixed on the next release
