### ISSUE TITLE
Error message: Base "Address 1" is empty!

### ISSUE THREAD

**Issue by annajeanine** [Progressus-io/postnl-for-woocommerce#140]
Versions: 
Wordpress: Version 6.3.1
WooCommerce: Version 8.1.0
PostNL plugin: 5.2.5

**Issue**
I have a recurring error during checkout with the message: "Base "Address 1" is empty!" and "This is not a valid address!". I have tried to resolve this error through a couple of ways with no success: 

- I have filled the first address line only
- I have filled the first and second address line
- I have enabled and disabled the PostNL plugin setting 

I don't get this error message when the plugin is not installed. 

Could someone help me on what is going wrong here, because I can't select a pickup location right now.

**Comment by annajeanine** [comment]
I have tested and gotten the same error with the following setups too: 

- Wordpress 6.3.1, WooCommerce 8.0.3
- - Wordpress 6.3.1, WooCommerce 8.0.0
- - Wordpress 6.2.2, WooCommerce 8.0.3

**Comment by annajeanine** [comment]
Found the error, I missed setting the store adres in settings. This and the users adres have the same error. I would suggest improving these error messages @Abdalsalaam @sal4sup

**Comment by Abdalsalaam** [comment]
@annajeanine Glad to hear it works! We will enhance the error messages 

thank you!

**Comment by Letsleds** [comment]
Hi,

When we're loading the checkout page, the PostNL plugin shows an error. 
![Github](https://github.com/user-attachments/assets/f58340d2-1eae-4f11-ab96-31cb28ce4e3f)

See attached, but this error already shown when no data is filled in.
This appears on this page when the shopping cart is filled: https://letsleds.nl/afrekenen/


How can we get rid of this bug?
