### ISSUE TITLE
Brievenbuspakje gives wrongly the possibility to drop at a PostNL point for Belgium customers

### ISSUE THREAD

**Issue by mihaflexxie** [Progressus-io/postnl-for-woocommerce#169]
Belgium customers can choose a Brievenbuspakje, but woocommerce sees it then as a normal package which is much more expensive for the seller.

**Comment by JorisPostNL** [comment]
Hi @mihaflexxie, thank you for bringing this to our attention. We would like to invite you to submit a case concerning this issue so our support team can have a look at it. You can enter the form at https://developer.postnl.nl/support/form/ and one of our colleagues will be with you within a business day.

Kind regards
Joris - PostNL
