### ISSUE TITLE
Bulk label print not possible

### ISSUE THREAD

**Issue by Bartb112** [Progressus-io/postnl-for-woocommerce#185]
<img width="630" alt="Scherm­afbeelding 2024-09-18 om 09 01 57" src="https://github.com/user-attachments/assets/ea514212-83a8-4e06-aaba-a0938d9c1955">
Its not possible to download a bulk labels. in last update,
5.6.0 (2024-09-17)

**Comment by JorisPostNL** [comment]
Hi @Bartb112, thank you for bringing this to our attention. Our developers are writing a fix for this issue which will be released as soon as possible

Kind regards
Joris - PostNL
