### ISSUE TITLE
Retourlabel

### ISSUE THREAD

**Issue by Bartb112** [Progressus-io/postnl-for-woocommerce#187]
When we make labels automatic create return label, even when the box return label is not checked.
In sigle label create and in bulk.

**Comment by Bartb112** [comment]
<img width="822" alt="Scherm­afbeelding 2024-09-18 om 11 12 04" src="https://github.com/user-attachments/assets/75947df7-9d97-48c2-bb0a-dd7b99aa9305">
<img width="522" alt="Scherm­afbeelding 2024-09-18 om 11 09 48" src="https://github.com/user-attachments/assets/a61f8cab-9abe-4daf-8e64-7dd3dd8c0dd1">

**Comment by JorisPostNL** [comment]
Hi @Bartb112, this was decided during the development of the new return products for technical reasons. If you do not wish to use Label in the Box we suggest setting it to None and sending a Smart Return barcode to the consumer if they need to return it, or setting it to Shipping & Return labels which remove the need for a secondary label to return parcels altogether. If these methods are not compatible with your business please let us know and we will look for an alternative

Kind regards
Joris - PostNL

**Comment by Bartb112** [comment]
@JorisPostNL What i mean he print auto the return label.
@JorisPostNL als ik bulk aan maak of een singel dan doet hij ondanks er geen retour opties zijn geselecteerd een retour label aanmaken.

**Comment by JorisPostNL** [comment]
@Bartb112 Dank voor de toelichting. Zoals aangegeven is ervoor gekozen tijdens het ontwikkelen om de geselecteerde retourmethode standaard te activeren voor iedere order. Indien dit onwenselijk is kan er gebruik gemaakt worden van de optie "Geen" in combinatie met het ad hoc versturen van een Smart Return wanneer een klant dit nodig heeft, of van Heen & Terug-labels, waarmee met één enkele label een pakket verstuurd en geretourneerd kan worden. Indien geen van deze opties jullie voorkeur heeft horen we dit graag.

Vriendelijke groet
Joris - PostNL

**Comment by Bartb112** [comment]
@JorisPostNL Die optie GEEN heb ik geselecteerd, maar dan blijft die de retourlabel aanmaken.
<img width="1226" alt="Scherm­afbeelding 2024-09-18 om 11 49 29" src="https://github.com/user-attachments/assets/3c04f82b-ec2a-45bf-9dca-d2c38c67a620">
En ik heb de wijzigingen opgeslagen.

**Comment by JorisPostNL** [comment]
@Bartb112 Ah zo, dank voor de toelichting. We gaan hier een fix voor laten schrijven, veel dank voor het onder de aandacht brengen hiervan!

Vriendelijke groet,
Joris - PostNL

**Comment by Bartb112** [comment]
@JorisPostNL geen dank, is ook in eigen belang :)

**Comment by rvdsteege** [comment]
Our client mentioned the same issue today; return labels being created while "Standaard retour optie" is set to "Geen".

I noticed this code for bulk action and order list table action button, but the issue also occurs when creating a label through the meta box on the order details page:

https://github.com/Progressus-io/postnl-for-woocommerce/blob/91f0f11b44222e4873a11eff53e0179e09ed24e1/src/Order/Bulk.php#L627

Hope to see this fixed soon — thank you!

**Comment by JorisPostNL** [comment]
Hi @rvdsteege @Bartb112, we have now released the fix for labels being generated while the option is set to None.

Kind regards
Joris - PostNL

**Comment by smakman** [comment]
@JorisPostNL, I'm still having this issue with version 5.6.2. Has the fix already been released?

**Comment by Bartb112** [comment]
@smakman in instellingen postNL moet je hem op geen retour label zetten en dan is het goed.

**Comment by JorisPostNL** [comment]
Hi @smakman, like @Bartb112 notes this issue should be fixed by now since our last release. If there are still Label in the Box-labels being created for **new orders** while the return option is set to None, please fill out the form at https://developer.postnl.nl/support/form/ so one of our colleagues from tech support can investigate the issue for you.

Kind regards
Joris - PostNL
