### ISSUE TITLE
House number shown twice on shipping label

### ISSUE THREAD

**Issue by smakman** [Progressus-io/postnl-for-woocommerce#189]
When generating a shipping label, the house number is shown twice on the shipping label when shipping to a home address. Is there a fix for this?

**Comment by JorisPostNL** [comment]
Hi @smakman, thank you for your inquiry. There are several possible causes for duplicate house numbers which will have to be examined by our tech support. If you fill out the form at https://developer.postnl.nl/support/form/ one of our colleagues will investigate the issue for you.

Kind regards
Joris - PostNL
