### ISSUE TITLE
Error on Checkout page

### ISSUE THREAD

**Issue by Letsleds** [Progressus-io/postnl-for-woocommerce#190]
![Github](https://github.com/user-attachments/assets/6edc033f-f5b2-408b-936a-1c7e08fd1630)

When we're loading the checkout page, the PostNL plugin shows an error.

See attached, but this error already shown when no data is filled in.
This appears on this page when the shopping cart is filled: https://letsleds.nl/afrekenen/

How can we get rid of this bug?

**Comment by JorisPostNL** [comment]
Hi @Letsleds, thank you for your inquiry. We would like to invite you to post this inquiry on https://developer.postnl.nl/support/form/ so our colleagues from tech support can investigate the issue for you. If necessary our tech support will file a support request with our developers if the issue needs to be investigated further.

Kind regards
Joris - PostNL
