### ISSUE TITLE
Does not support cart and checkout blok

### ISSUE THREAD

**Issue by joost-abrahams** [Progressus-io/postnl-for-woocommerce#197]
Will this be fixed or communicated?

**Comment by joost-abrahams** [comment]
You claim it is compatible by : WC tested up to: 9.3

**Comment by JorisPostNL** [comment]
@joost-abrahams Thank you for bringing this to our attention. To make things more clear we have made a note of the incompatibility on the first page of the plug-in manual.

Kind regards
Joris - PostNL

**Comment by joost-abrahams** [comment]
About this subject: https://developer.woocommerce.com/2023/11/06/faq-extending-cart-and-checkout-blocks/

Thanks you for making the note in the manual.

**Comment by joost-abrahams** [comment]
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/shipping.md

Testing block integration checklist
