### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by Bartb112** [Progressus-io/postnl-for-woocommerce#23]
nice new plugin.

i missing or not working
1. company name on label when print
2. option for fast deliver before 10:00 or 12:00 hour
3. option sign on deliver for 
4.Set order on ready, when label is print.

**Comment by Abdalsalaam** [comment]
Hi @Bartb112 ,
FYI, we added company name to the label, also now you can enable "Morning delivery" for the fast delivery.
