### ISSUE TITLE
Class Main not found

### ISSUE THREAD

**Issue by atxvisions** [Progressus-io/postnl-for-woocommerce#24]
After installing the plugin through the instructions, it says PostNLWooCommerce\Main not found in /postnl-for-woocommerce/postnl-for-woocommerce.php line 46.
Even after installing through composer and such, disabling and enabling themes and plugins the error persists.

Am I missing something? This is the stack trace with some domain data cut out.
#0 /public_html/wordpress/wp-includes/class-wp-hook.php(308): PostNLWooCommerce\postnl('')
#1 /public_html/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 /public_html/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 //public_html/wordpress/wp-settings.php(480): do_action('plugins_loaded')

**Comment by atxvisions** [comment]
I found out that this line require_once  'vendor/autoload.php'; in postnl-for-woocommerce.php needs to be
require_once  plugin_dir_path(__FILE__) . 'vendor/autoload.php';

Once i make this change, the website loads again

**Comment by Abdalsalaam** [comment]
Fixed, thank you!
