### ISSUE TITLE
No return label for letterbox parcels

### ISSUE THREAD

**Issue by stijneikelboom** [Progressus-io/postnl-for-woocommerce#45]
When a label is generated with both the letterbox parcel and the return label option enabled, no return label is included in the PDF. This does work properly for non-letterbox parcels.

It is currently unclear to me where this issue originates, but it must be that the `create_return_label` option is ignored somewhere in the pipeline of generating a letterbox parcel label. Can you please investigate and fix?

Additionally, it would be useful to allow adding a return label after a regular label has already been generated. This is relevant in cases where the sender only generates return labels on request. This is currently only possible by deleting the original label, which is not always feasible.

**Comment by stijneikelboom** [comment]
Could you please follow up on this issue? Our customer would like to start generating return labels for letterbox parcels. Thanks!

**Comment by Abdalsalaam** [comment]
Hi @stijneikelboom , I asked PostNL for this , and this is there response :
"we currently do not offer Label in the Box (which is what you get when you enter the ReturnBarcode line) in conjunction with Letterbox Parcels."
