### ISSUE TITLE
Cut off time not set will result in an error on the order page.

### ISSUE THREAD

**Issue by gvenk** [Progressus-io/postnl-for-woocommerce#46]
If the cut-off time is not set, there will be an error on the order page: 

![2023-02-12 10 40 52 Afrekenen ](https://user-images.githubusercontent.com/9460/218695473-01ddbba7-1234-4e9e-804b-ffaf11a948da.png)

I don't know if the cut-off time always needs to be set in this plugin, then it would be a good idea to give some notice about this in the wp-admin.

**Comment by sambirempo** [comment]
I have the same issue. Only option is to disable POSTNL shipment method and use the bulk action in woocommerce to create a label manually. Else shoppers will be annoyed by the "Wrong format for cut off time!" error and the whole page is being shifted.

**Comment by Abdalsalaam** [comment]
@gvenk  @sambirempo 
can you check the " Cut Off Time  " field in the plugin settings ? ( WooCommerce > Settings > Shipping > PostNL )
it should be HH:MM formatted ex : "21:00"
