### ISSUE TITLE
PostNL element not showing in order page

### ISSUE THREAD

**Issue by Error-0418** [Progressus-io/postnl-for-woocommerce#47]
Hii everyone,

Unfortunately since a couple of days the postNL element on the order page has gone missing.
I've tried to look at the screenoptions at the top to see if I had to manually add it, but it's not showing between all the other elements/options. I've also tried a reinstall of the plugin, but that hasn't changed anything.

I'm afraid it may have something to do with the updates from a couple of days ago.

**Comment by Abdalsalaam** [comment]
Hi @Error-0418 , 
Did you use the old plugin version before (From WP.org store) then you updated to the latest version ?

**Comment by coos-max** [comment]
Hi,

Same problem here: no labels on order page.
Had to rollback to version 4.4.8, originally installed before 4.4.2 and updated to eventually 5.1.2
From 5.0.0 no label on order page.

**Comment by Error-0418** [comment]
Hello @Abdalsalaam,

I think so, yes.

**Comment by Abdalsalaam** [comment]
@Error-0418 @coos-max 
Thank you for reporting this, We are working on it.

**Comment by Abdalsalaam** [comment]
Hi @Error-0418 , 
v5.2.0 released and it contains a fix for this issue.
