### ISSUE TITLE
How is the PostNL tracking number stored in Woocommerce

### ISSUE THREAD

**Issue by Snoopy1975-2** [Progressus-io/postnl-for-woocommerce#80]
Someone is changing an order pick plugin for me, so that when i'm ready with picking the products,  i have to scan the shipping label to conform it's the right label for this order. But to make this possible he needs to know how the PostNL tracking code is stored in woocommerce. Can someone help me with this?

**Comment by sdev1930** [comment]
I am developing the code.  I need to know how the tracking number is stored in Wordpress.  Normally it's a custom meta field tied to the order number but I cannot find this in the plugin.

**Comment by Abdalsalaam** [comment]
Hello  @Snoopy1975-2 and @sdev1930 ,
all plugin data saved in `_postnl_order_metadata` metadata, and you can find the tracking number in $array['labels']['label']['barcode']
