### ISSUE TITLE
Undefined array key causing loop inside checkout fragments

### ISSUE THREAD

**Issue by joerivanderstek** [Progressus-io/postnl-for-woocommerce#81]
Hi,

I've installed the plugin on one of my client's websites. It seems like the array key 'postnl_delivery_day_type' on line 387 of src\Frontend\Container.php isn't getting checked if it's set. 

When running a blank local installation with the same settings it works fine but on the staging environment on the Kinsta server it causes an loop inside the WooCommerce checkout fragments. The error still occurs when deactivating all plugins and changing the theme to twenty-twenty-two. Changing the code to check if the array key is defined gets rid of the loop and shows the shipping dates when the fragment updates.

Below the error message without sensitive information:
`2023/04/23 11:03:34 [error] 88520#88520: *15289 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined array key "postnl_delivery_day_type" in /www/XXX-website/public/wp-content/plugins/woo-postnl/src/Frontend/Container.php on line 387" while reading response header from upstream, client: XXX-ip-address, server: XXX-website, request: "POST /?wc-ajax=update_order_review HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8.0-fpm-XXX-website.sock:", host: "XXX-website", referrer: "XXX-website/afrekenen/"`

If there's something you need from me to fix the issue please let me know!

Cheers, Joeri

**Comment by Abdalsalaam** [comment]
Hi @joerivanderstek 
thank you for reporting this, will be fixed in the next release, you can use this [branch](https://github.com/Progressus-io/postnl-for-woocommerce/tree/develop) it contains the fix.
